services:
    comet:
      build:
        context: .
        dockerfile: deploy/Dockerfile
      container_name: bot
      restart: on-failure
      environment:
        TOKEN: ${TOKEN}
        MONGO_URI: ${MONGO_URI}
      